### ISSUE TITLE
How to get gogoanime id?

### ISSUE THREAD

**Issue by WarLock03** [amvstrm/docs#7]
Hello, wanna ask on how can I get gogoanime id? There so many gogoanime domain and the url's not providing the id

**Comment by NYT92** [comment]
Gogoanime switches domains a lot of the time and now they changed to anitaku.to for some reason so there is a good chance that all of the IDs would stay the same.

If you want the ID from the gogoanime : ``<Official GOGOANIME website>/category/<ID>``
If you want the Watch ID from gogoanime : ``<Official GOGOANIME website>/<ID>-episode<number of episode>``

_Image from gogotaku.info [blog post](https://gogotaku.info/announcement/breaking-gogoanime-domain-change-jul-2023-update-nov-2023.html)_

![image-1701054753](https://github.com/amvstrm/docs/assets/53612429/09f3aba2-7ba9-403d-bca0-9f2aef6c0598)
